### ISSUE TITLE
can't log the same string twice

### ISSUE THREAD

**Issue by japaric** [japaric/stlog#1]
### STR

``` rust
fn foo() {
    info!(LOGGER, "Hello");
}

fn bar() {
    warn!(LOGGER, "Hello");
}
```

``` console
$ xargo build
error: symbol `Hello` is already defined
 --> src/main.rs:4:1
  |
4 | static BAR: u8 = 0;
  | ^^^^^^^^^^^^^^^^^^^

error: Could not compile `hello`.
```

**Comment by japaric** [comment]
My idea to fix this was to prepend the filename and the line number to the message so the previous program would actually log:

``` console
$ cat /dev/ttyUSB0 | stcat -e file
INFO(src/main.rs:7) Hello
WARN(src/main.rs:8) Hello
```

but it's not possible to write `#[export_name = concat!(..)]` in a macro rules. Trying to work around this problem by concatenating strings outside the macro and then passing the concatenated string to the macro results in rust-lang/rust#42164.

**Comment by japaric** [comment]
Triage: we can do this using procedural macros that expand into expressions but those are not available so fixing this is blocked on that being stabilized.

**Comment by jonas-schievink** [comment]
Triage: procedural macros are now stable :tada:

**Comment by japaric** [comment]
This has been implemented behind the `spanned` feature in master but requires the unstable `proc_macro_span` feature in the library and the `proc_macro_hygiene` at call site.
